apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-v1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-v1
  template:
    metadata:
      labels:
        app: hello-world-v1
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: autoscaling-node-pool
      containers:
      - name: hello-world
        image: nmatsui/hello-world-api
        env:
        - name: MESSAGE
          value: "Hello from the Version 1 environment"
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "100m"
            memory: "1Gi"
          requests:
            cpu: "10m"
            memory: "100Mi"
