apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hello-world-v2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-world-v2
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
