apiVersion: v1
kind: Service
metadata:
  name: hello-world
  namespace: default
spec:
  selector:
    app: hello-world-v1 
  ports:
    - protocol: TCP
      port: 3000      
      targetPort: 3000
  type: LoadBalancer
